language: go

go:
    - 1.5

addons:
    apt:
        packages:
            - ruby1.9.3-full
            - python2
            - python3
            - nodejs-legacy

env:
    - GOARCH=amd64

before_script:
    - node --version
    - python2 --version
    - python3 --version
    - ruby --version
    - go version
    - mkdir libs
    - cd libs
    - git clone https://github.com/SSSaaS/sssa-golang
    - git clone https://github.com/SSSaaS/sssa-python
    - git clone https://github.com/SSSaaS/sssa-js
    - git clone https://github.com/SSSaaS/sssa-ruby
    - cd sssa-js
    - npm install
    - cd ../../

script:
    - go run ./go-libtest.go ./specs/travis/*.json
