language: node_js

node_js:
    - "4.0"

addons:
    apt:
        packages:
            - ruby1.9.3-full
            - python2
            - python3
            - golang-go

env:
    - GOARCH="amd64" GOPATH="/home/travis/.gimme/versions/go1.4.1.linux.amd64/"

before_script:
    - node --version
    - python2 --version
    - python3 --version
    - ruby --version
    - go version
    - go get github.com/SSSaaS/go-libtest
    - cd $GOPATH/src/github.com/SSSaaS/go-libtest
    - mkdir libs
    - cd libs
    - git clone https://github.com/SSSaaS/sssa-golang
    - git clone https://github.com/SSSaaS/sssa-python
    - git clone https://github.com/SSSaaS/sssa-js
    - git clone https://github.com/SSSaaS/sssa-ruby
    - cd sssa-js
    - npm install
    - cd ../
    - cd sssa-golang
    - go test
    - cd ../sssa-python
    - python2 ./utils_tests.py
    - python2 ./sssa_tests.py
    - python3 ./utils_tests.py
    - python3 ./sssa_tests.py
    - cd ../sssa-ruby
    - ruby ./tests/all.rb
    - cd ../sssa-js
    - node ./test/sssa.js
    - cd ../../

script:
    - go run ./go-libtest.go ./specs/travis/*.json
